# Generated by Django 3.2.8 on 2021-12-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=64)),
                ('command', models.CharField(max_length=64)),
                ('key', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='EnterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=64)),
                ('key', models.CharField(max_length=64)),
            ],
        ),
    ]
