# Generated by Django 3.2.8 on 2021-12-11 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterlog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
