# Generated by Django 3.2.8 on 2021-12-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='somemodel',
            name='age',
            field=models.IntegerField(default=20, verbose_name='Age'),
        ),
    ]
