# Generated by Django 3.2.8 on 2021-12-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0002_enterlog_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterlog',
            old_name='key',
            new_name='event',
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=64, verbose_name='Your TOKEN'),
        ),
    ]
