# Generated by Django 3.2.8 on 2021-12-11 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0003_auto_20211211_1343'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnterLog',
            new_name='Log',
        ),
        migrations.DeleteModel(
            name='CommandLog',
        ),
    ]
