# Generated by Django 3.2.8 on 2021-12-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0004_auto_20211211_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.CharField(default='', max_length=64, verbose_name='Your GROUP'),
        ),
    ]
