# Generated by Django 3.2.8 on 2021-12-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0005_auto_20211211_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.CharField(max_length=64, verbose_name='Your GROUP'),
        ),
    ]
